ktor:
  deployment:
    port: 8080
  application:
    modules:
      - com.terabyte.MainKt.module

jwt:
  secret: ${JWT_SECRET}
  issuer: "product-store-backend-app"
  realm: "product-store"

database:
  dbType: sqlite
  url: "jdbc:sqlite:./my_database.db"
  driverClassName: "org.sqlite.JDBC"
  maxPoolSize: 1

kind: Application